### ISSUE TITLE
Fix KeyboardInterrupt Error

### ISSUE THREAD

**Issue by arch-master** [arch-master/eBooker#10]
When exiting eBooker with <kbd>^C</kbd>, eBooker exits with the following error:

    eBooker > ^CTraceback (most recent call last):
      File "ebooker.py", line 65, in <module>
        print(helpString)
      File "ebooker.py", line 16, in get_input
        return raw_input(message)
    KeyboardInterrupt

Is there any to stop that error and show the output of the `exit` command instead?

**Comment by arch-master** [comment]
I sort-of solved the problem with a try-except statement that stopped the error from showing, but whatever I answer for the `exit` command exits the program.

**Comment by H4XDev** [comment]
Have you tried placing the function in a thread? Python threads can't be interrupted. If you implement the threading you have to wait for the thread to finish. You'll need the imports time and threading. 

For more info see: 
http://stackoverflow.com/questions/842557/how-to-prevent-a-block-of-code-from-being-interrupted-by-keyboardinterrupt-in-py

**Comment by arch-master** [comment]
@H4XDev Thanks! I'll try that...

**Comment by H4XDev** [comment]
Let me know if it works! I'd love to help :).

**Comment by H4XDev** [comment]
I've managed to make somewhat of a workaround for the Ctrl+C problem. 

If you make a function RestartProgram and call the function when a KeyboardInterrupt exception occurs, you can just cleanly restart the program without having to kill it.

Method:

def RestartProgram():
    python = sys.executable
    os.execl(python, python, * sys.argv)

I've tested it locally and it works for me, it is still within a try/catch however. If you want the file I'll send it.

**Comment by arch-master** [comment]
@H4XDev That's a good workaround, but I want the program to still exit. I'll use your thread idea.

**Comment by colexyz** [comment]
Use the KeyboardInterrupt error to exit eBooker.

i.e.
```
import sys
try:
  raw_input(message) # ^C to interrupt keyboard/exit
except KeyboardInterrupt: # Keyboard interrupted
  print(something) # Print output
  sys.exit(1) # Safely exit
```

**Comment by arch-master** [comment]
@colexyz I did that. Thanks!
