### ISSUE TITLE
remove repetitive tester.test() calls

### ISSUE THREAD

**Issue by aidaekay** [arch-master/eBooker#15]
tester.test() is called on almost all of the input test commands. 

could we possibly reiterate this into a while loop or something that checks to see if all necessary files are there before taking in user input? i counted ~24 times that it's called in total. not even really sure if this function is necessary. 

if anybody has anybody better ideas of checking to make sure the files are there without having to constantly call this function, let me know and i can work on the coding for it.

**Comment by aidaekay** [comment]
sorry so just saw that there's also a tester.py class, but i've tried deleting it then running and it works the same. can somebody explain??

**Comment by vatdaell** [comment]
@aidaekay I believe that the program cannot guarantee that the files that it checks after every command will exist. The repetitive checking might be the only way to guarantee if the required files are not missing as the program executes each given command.

**Comment by arch-master** [comment]
@aidaekay The tester.py file is for CircleCI.
