### ISSUE TITLE
Refactoring of ebooker.py to multiple files 

### ISSUE THREAD

**Issue by vatdaell** [arch-master/eBooker#16]
I was looking at the project and I think some of the code can be refactored into different files for easier management. Also I think we might need to make a separate Command class in order to make calling commands easier in the ebooker.py file.

**Comment by belyak** [comment]
I think that refactoring is needed too. 
But classes are not needed imho.
You can register all commands with decorator:

    _commands = {}
    def command(name):
        def inner(func):
            _commands[name] = func
            return func

  
    @command('custom')
    def my_custom_command():
         # some useful code

 add then evaluate user command without multiple boring if/else:

    try:
        handler = _commands[keyword]
    except KeyError:
        print("Unknown command!")
        continue  # to the input

    handler()  # call command

**Comment by vatdaell** [comment]
Now that I think about it your idea seems the best.

**Comment by BenEast** [comment]
I'm going to look into refactoring before the project gets too large.
