### ISSUE TITLE
Module os has no attribute 'geteuid' error

### ISSUE THREAD

**Issue by dhananjayhegde** [arch-master/eBooker#28]
With Python 3.6.2, when I run the command `> python ebooker.py`  on development branch, I get the error 

> module os has no attribute 'geteuid'

Traceback:

`Traceback (most recent call last):
  File "ebooker.py", line 54, in <module>
    install_markdown()
  File "ebooker.py", line 25, in install_markdown
    if os.geteuid()==0:
AttributeError: module 'os' has no attribute 'geteuid'`

**Comment by dhananjayhegde** [comment]
I found in Python documentation that os.geteuid() is available only for Unix.  I am running Windows 7.

[os.geteuid()](https://docs.python.org/3.6/library/os.html?highlight=os#os.getuid)

**Comment by arch-master** [comment]
This is strange, because this function does not seem to be in the code. Thanks! I'll take a look 😄

**Comment by arch-master** [comment]
Just noticed #29. Let's see if it works.
