### ISSUE TITLE
Code Transfers

### ISSUE THREAD

**Issue by arch-master** [arch-master/eBooker#4]
Can someone please find some way to transfer non-platform-specific Python code between files automatically? What I mean is, can you make it so typing `print("Hello!")` in some place will automatically put that code in the right place in both `cmd-mac-*nix.py` _and_ `cmd-windows.py`? Thanks! **Remember to commit to the development branch and then merge!**

**Comment by p53ud0k0d3** [comment]
@arch-master Can you be more specific ? 
So do you want the tool to be a single script (eg: ebooker.py) which can be run on windows as well as mac and Unix, instead of separate script for windows and unix?

**Comment by arch-master** [comment]
@p53ud0k0d3 Yes. That's right. I think N135 solved it in #7...
