### ISSUE TITLE
Double quotes

### ISSUE THREAD

**Issue by p53ud0k0d3** [arch-master/eBooker#6]
Users have to type everything inside double quotes. 
For eg : "help" instead of help
              "y" instead of y

This is very misleading and difficult to cope up with. All other utilities support input without quotes. So please add facility to give input without quotes.

**Comment by N135** [comment]
If you're running this using python 2.7, then that will be the case. In python 3, it runs normally. 

Would a python 2.7 version be something that would be useful? If so, I've done a lot of work related to it already and could merge in a 2.7 version.

**Comment by arch-master** [comment]
@N135 Good point. Please do that. Maybe we could use this code to detect the version #:

    import sys
    if sys.version_info[0] < 3:
        NOT PYTHON 3
    else:
        PYTHON 3 OR ABOVE
👍

**Comment by N135** [comment]
Great idea! I'll add that in soon!

**Comment by arch-master** [comment]
@N135 Thanks!

**Comment by arch-master** [comment]
@p53ud0k0d3 Fixed in #9 by @N135.
